In [6]:
from data import SVMDataset
from torch.utils.data import DataLoader

In [7]:
dataset = SVMDataset(1000, 0.5)
dataloader = DataLoader(dataset, batch_size = 32, shuffle =True)

import torch
torch.set_default_tensor_type(torch.FloatTensor)
epochs = 10
for epoch in range(epochs):
    for iter, data in enumerate(dataloader):
        print(data[1].shape)

In [20]:
from svm import LinearSVM
model = LinearSVM()

In [27]:
X = torch.Tensor([[2,3],[4,5]])

print(model(X).t().shape)
print(model(X))
print(model(X).t())
print(model(X).t()*torch.Tensor([1,-1]))

torch.Size([1, 2])
tensor([[-1.7332],
        [-3.1942]], grad_fn=<AddmmBackward>)
tensor([[-1.7332, -3.1942]], grad_fn=<TBackward>)
tensor([[-1.7332,  3.1942]], grad_fn=<MulBackward0>)
